### PR TITLE
Create github CI equivalent to current circle CI

### PR DESCRIPTION
**Pull request by JonasVautherin**
WIP

### CODE REVIEW

**Comment by JonasVautherin** [comment]
FYI @thewtex: It's based upon your PR, but other than that I think that it does the same thing as the current circleci setup :blush:. I'll open a PR once yours is merged so I can get a proper review.

**Comment by thewtex** [comment]
@JonasVautherin beautiful!!

**Comment by JonasVautherin** [comment]
Apparently I can't change the target repository. Let me close and re-open.

**Comment by JonasVautherin** [comment]
New PR is [here](https://github.com/dockcross/dockcross/pull/469).

**Pull request closed without merging**
